### ISSUE TITLE
PPQ precision at regular BPM

### ISSUE THREAD

**Issue by ghost** [agraef/pd-jacktime#1]
Hi,
I do not know if it is an issue with jacktime per se or the limitations of Pd, but I want to use PPQ - which jacktime actually gets on my setup - as a clock multiplier. So tick => mod => sel 0 => bang to see if it works.

It works a really low BPM. Once too fast, it misses the mark.

I'll look into the code see if I can implement a multiplier before it its Pd, but I do not know much about Lua.

**Comment by agraef** [comment]
I'm not really sure that I understand your problem, but it sounds like you're trying to detect fractional beats? But which ones? You didn't say what modulus you're using there, and what the BPM is at which you start running into trouble. 

In any case, note that this is a control object which uses a Pd timer internally. Thus it runs with a certain frequency between Pd's dsp ticks. As you can see if you take a look at jacktime.pd_lua, the hard-coded update period is 10 msecs, but you can specify a lower value as jacktime's creation argument if you want. But even then you can't make it go more frequently than Pd's dsp ticks (i.e., every 64 samples by default).

So at that rate the object will then poll jack transport for the current tick number (along with all the other data), whatever that happens to be. There's no guarantee that it will hit a certain tick number *exactly*, 0 or any other. So you need to divide the ticks by the ppq value, then multiply by whatever factor corresponds to the partial beats you're trying to detect, round off to an integer and then detect when that value changes. E.g., something like this should do the trick if you're trying to detect 32ths (8th beats):
 
![image](https://user-images.githubusercontent.com/2853977/36051291-dd202024-0de9-11e8-915e-c00ad4adced8.png)

Does that solve your problem?

Otherwise, if you need better accuracy, then a control-rate object won't do the trick, no matter how hard you try, so you'll probably have to roll your own (probably in C) which either uses callbacks (if the jack transport API even provides that, I haven't checked) or polls at audio rate during dsp ticks.

**Comment by ghost** [comment]
Sorry, it wasn't that clear. I tried to use the ticks output directly, doing as you made on your example, and did not get reliable results. As you've just shown and explained, I was wrong to do so.
Thank you for your great answer !
